# Generated by Django 6.0.1 on 2026-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="nom",
            field=models.CharField(default="Inconnu", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="prenom",
            field=models.CharField(default="Inconnu", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="telephone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
